# Generated by Django 5.0.14 on 2025-12-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_hero', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('about_us_banner', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('announcement_bar_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
