# Generated by Django 5.0.14 on 2025-12-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('hero_title', models.CharField(default='The Art of Persian Pastry', max_length=200)),
                ('hero_subtitle', models.TextField(default='Delicate saffron, cardamom, and rosewater masterpieces crafted for the most discerning palates.')),
                ('secondary_banner', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('promo_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Homepage Configuration',
                'verbose_name_plural': 'Homepage Configuration',
            },
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
    ]
