# Generated by Django 5.0.14 on 2025-12-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_homeconfig_delete_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='The Art of Persian Pastry', max_length=200)),
                ('hero_subtitle', models.TextField(default='Delicate saffron, cardamom, and rosewater masterpieces crafted for the most discerning palates.')),
                ('hero_main_image', models.ImageField(blank=True, null=True, upload_to='content/hero/')),
                ('hero_button_text', models.CharField(default='Explore the Collection', max_length=50)),
                ('about_title', models.CharField(default='Handcrafted with Generations of Tradition', max_length=200)),
                ('about_description', models.TextField(default='Every item at Natalie Bakery is a labor of love...')),
                ('about_side_image', models.ImageField(blank=True, null=True, upload_to='content/about/')),
                ('contact_tagline', models.CharField(default='Visit Our Boutique', max_length=255)),
                ('maps_url_override', models.URLField(blank=True, help_text='Custom Google Maps embed URL', null=True)),
                ('footer_tagline', models.CharField(default='Authentic Persian flavors meet modern culinary artistry.', max_length=255)),
                ('instagram_handle', models.CharField(default='@nataliebakery.toronto', max_length=100)),
            ],
            options={
                'verbose_name': 'Global Site Content',
                'verbose_name_plural': 'Global Site Content',
            },
        ),
        migrations.CreateModel(
            name='UIAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Unique identifier for this asset (e.g., 'footer-logo')", unique=True)),
                ('image', models.ImageField(upload_to='content/ui/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='HomeConfig',
        ),
        migrations.AddField(
            model_name='product',
            name='square_id',
            field=models.CharField(blank=True, help_text='Square Catalog Object ID', max_length=100, null=True),
        ),
    ]
