# Generated by Django 5.0.14 on 2025-12-19 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sitecontent_uiasset_delete_homeconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_side_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='content/about/'),
        ),
        migrations.CreateModel(
            name='SiteFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('site_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.sitecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('section', models.CharField(default='story', help_text="e.g. 'story', 'hero', 'footer'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('site_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.sitecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
