# Generated by Django 5.0.14 on 2025-12-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sitecontent_about_side_image_2_sitefeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_options',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.cakeoption'),
        ),
    ]
