# Generated by Django 5.0.14 on 2025-12-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_created_at_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('ea', 'each'), ('kg', 'kg'), ('lb', 'lb')], default='ea', max_length=10),
        ),
    ]
